name: Branch CI
on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    name: Build & Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
    - name: Cache SBT ivy cache
      uses: actions/cache@v2
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('dependencies.sbt') }}
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('dependencies.sbt') }}
    - name: Cache Coursier
      uses: actions/cache@v2
      with:
        path: ~/.cache
        key: ${{ runner.os }}-coursier-${{ hashFiles('dependencies.sbt') }}
    - name: Cache .jabba
      uses: actions/cache@v2
      with:
        path: ~/.jabba
        key: ${{ runner.os }}-jabba-${{ hashFiles('dependencies.sbt') }}
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: openjdk@
    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - name: Compile & Test
      run: csbt compile test
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always() # Pick up events even if the job fails or is canceled.
