on:
  push:
    branches-ignore:
      - "main"

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Env variables
        run: |
          echo 'GIT_COMMIT_MESSAGE<<GIT_COMMIT_MESSAGE_DELIMITER' >> $GITHUB_ENV
          git log -1 --pretty=%B | cat >> $GITHUB_ENV
          echo 'GIT_COMMIT_MESSAGE_DELIMITER' >> $GITHUB_ENV
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""                                 # If blank, default: triggered branch
          destination_branch: "main"                      # If blank, default: master
          pr_title: "Merge ${{ github.ref }} into main"   # Title of pull request
          pr_body: $GIT_COMMIT_MESSAGE                      # Full markdown support, requires pr_title to be set
          pr_reviewer: "reformedcoder,jaredmdobson"         # Comma-separated list (no spaces)
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          pr_draft: true                                    # Creates pull request as draft
          pr_allow_empty: true                              # Creates pull request even if there are no changes
          github_token: ${{ secrets.GITHUB_TOKEN }}
